### ISSUE TITLE
Add pre-registration link

### ISSUE THREAD

**Issue by atoneyd** [HackNC/fall2023#25]
- [x] Create a button/link in front of the committee interest form
- [x] Use this link: https://forms.gle/F7mTHdNWymW8km7z5
- [x] Style Register button according to new design.

**Comment by aryasalian** [comment]
Can you add a description to the task? No clue what the pre-registration link is :\

**Comment by atoneyd** [comment]
> Can you add a description to the task?

Done

**Comment by aryasalian** [comment]
TYSM!
