### ISSUE TITLE
Link MLH Code of Conduct

### ISSUE THREAD

**Issue by jadekeegan** [HackNC/fall2023#40]
# Link MLH Code of Conduct
Link the MLH code of conduct to the text at the bottom of the page.

## Acceptance Criteria
- [x] Add the link to the MLH code of conduct
- [x] Style link color and hover

**Comment by atoneyd** [comment]
BTW, you can use the same link that we had from last year's website: https://static.mlh.io/docs/mlh-code-of-conduct.pdf
